# Generated by Django 5.1.2 on 2024-11-03 18:34

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("tag", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tag.BlogTaggedPage",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
