# Generated by Django 5.1.2 on 2024-10-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_foliopage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foliopage',
            name='tags',
        ),
    ]
