# Generated by Django 5.1.2 on 2024-10-08 21:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
