# Generated by Django 5.1.2 on 2024-10-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_service_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(blank=True, to='customers.service'),
        ),
    ]
