# Generated by Django 5.1.2 on 2024-10-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_invoice_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='customers.service'),
        ),
    ]
