# Generated by Django 5.1.2 on 2024-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_invoice_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Facture'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date', 'project__customer']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures'),
        ),
    ]
